# This file was generated by GoReleaser. DO NOT EDIT.
cask "raph" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "c1ce73cf41a160bcdff18b8a9a53d70786dd5bec41d0f64003b057d05b21389a"
      url "https://github.com/tesh254/raph/releases/download/v#{version}/raph_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b916091751b34769165eb42ce05971951e9ef8982b05b2138d2c71dc12b409f7"
      url "https://github.com/tesh254/raph/releases/download/v#{version}/raph_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "46387eed3dd0f469de57d24cea13137bcd76cda19f94de85fe8e5eec446b5fbf"
      url "https://github.com/tesh254/raph/releases/download/v#{version}/raph_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "123982ad2866329851dcc474f91f3afef10c35f495e6fe81fd0fe3da5108ede9"
      url "https://github.com/tesh254/raph/releases/download/v#{version}/raph_linux_arm64.tar.gz"
    end
  end

  name "raph"
  desc "Local-first graph-vector brain for coding agents"
  homepage "https://tesh254.github.io/raph/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "raph"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/raph"]
    end
  end

  # No zap stanza required

end
